apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  namespace: gitops-demo
  labels: {app: gitops-app, student: jingyou-ma}
spec:
  replicas: 2
  selector:
    matchLabels: {app: gitops-app}
  template:
    metadata:
      labels: {app: gitops-app, student: jingyou-ma}
    spec:
      containers:
        - name: app
          image: jingyouma/cse644-gitops-app:3.0.0-does-not-exist
          imagePullPolicy: IfNotPresent
          env:
            - {name: APP_VERSION, value: "3.0.0"}
            - {name: APP_MESSAGE, value: "GitOps update reconciled for Jingyou Ma"}
          ports:
            - {name: http, containerPort: 8888}
          readinessProbe:
            httpGet: {path: /healthz, port: http}
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet: {path: /healthz, port: http}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests: {cpu: 20m, memory: 32Mi}
            limits: {cpu: 200m, memory: 96Mi}
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-app
  namespace: gitops-demo
  labels: {app: gitops-app}
spec:
  selector: {app: gitops-app}
  ports:
    - {name: http, port: 8888, targetPort: http}
