apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application.yaml
  - observability.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml
  - name: grafana-datasource
    files:
      - datasource.yaml
  - name: grafana-dashboard-provider
    files:
      - dashboard-provider.yaml
  - name: grafana-dashboard
    files:
      - cse644-dashboard.json
generatorOptions:
  disableNameSuffixHash: true

